env:
  matrix:
    - PACKAGE=resource-store-redux
    - PACKAGE=resource-store-redux-thunk
  global:
    - CC_TEST_REPORTER_ID=0147c1550877b80fc473728cee5f8b70e716c2859e02e453658233bd7c20bcb1
language: node_js
node_js:
  - lts/*
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: lerna run test --scope $PACKAGE -- --coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
