export enum ResourceActionTypes {
  RESOURCE_REQUEST = '@RESOURCE/REQUEST',
  RESOURCE_SUCCESS = '@RESOURCE/SUCCESS',
  RESOURCE_FAILURE = '@RESOURCE/FAILURE',
  RESOURCE_CANCEL = '@RESOURCE/CANCEL',
}
